import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs/promises";

const ALLOWED_SUBJECTS = new Set(["biology", "chemistry", "physics"]);

interface TopicNotes {
    normal: string[];
    revision: string[];
}

type SubjectNotesJSON = Record<string, TopicNotes | Record<string, TopicNotes>>;

function findKey(obj: Record<string, unknown>, target: string): string | undefined {
    if (target in obj) return target;
    const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
    const t = norm(target);
    return Object.keys(obj).find((k) => norm(k) === t);
}

function getNotes(
    data: SubjectNotesJSON,
    topic: string,
    subtopic?: string | null
): TopicNotes | null {
    const topicKey = findKey(data as Record<string, unknown>, topic);
    if (!topicKey) return null;

    const entry = data[topicKey] as any;

    if (Array.isArray(entry?.normal)) return entry as TopicNotes;

    if (!subtopic) return null;

    const subKey = findKey(entry as Record<string, unknown>, subtopic);
    if (!subKey) return null;

    return entry[subKey] as TopicNotes;
}

function buildHtml(
    items: string[],
    topicLabel: string,
    subjectName: string,
    mode: string
): string {
    const rows = items
        .map(
            (item, i) => `
      <div class="item">
        <span class="num">${i + 1}</span>
        <span class="text">${item}</span>
      </div>`
        )
        .join("\n");

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${subjectName} – ${topicLabel}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Lato', sans-serif;
      font-size: 13px;
      color: #1f2937;
      background: #fff;
      padding: 48px 56px;
      line-height: 1.7;
    }

    header {
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 16px;
      margin-bottom: 28px;
    }

    header .subject {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #9ca3af;
      margin-bottom: 4px;
    }

    header h1 {
      font-size: 20px;
      font-weight: 700;
      color: #111827;
    }

    header .badge {
      display: inline-block;
      margin-top: 8px;
      padding: 3px 10px;
      border-radius: 999px;
      font-size: 11px;
      font-weight: 700;
      background: ${mode === "revision" ? "#fef3c7" : "#d1fae5"};
      color: ${mode === "revision" ? "#92400e" : "#065f46"};
    }

    .item {
      display: flex;
      gap: 12px;
      align-items: flex-start;
      padding: ${mode === "revision" ? "9px 12px" : "4px 0"};
      ${mode === "revision" ? "border-radius: 6px; background: #f9fafb; margin-bottom: 6px;" : "margin-bottom: 2px;"}
    }

    .num {
      ${mode === "revision" ? "display:flex;align-items:center;justify-content:center;flex-shrink:0;width:20px;height:20px;border-radius:50%;background:#fef3c7;color:#92400e;font-size:10px;font-weight:700;margin-top:2px;" : "display:none;"}
    }

    .text {
      flex: 1;
    }

    mark {
      background: ${mode === "revision" ? "#fef08a" : "#bbf7d0"};
      border-radius: 2px;
      padding: 0 2px;
    }

    footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e5e7eb;
      font-size: 10px;
      color: #9ca3af;
    }
  </style>
</head>
<body>
  <header>
    <p class="subject">${subjectName}</p>
    <h1>${topicLabel}</h1>
    <span class="badge">${mode === "revision" ? "⚡ Revision Notes" : "📖 Full Notes"}</span>
  </header>

  <main>${rows}</main>

  <footer>
    Generated by SciLearn · GCE A/L Exam Preparation
  </footer>
</body>
</html>`;
}

export async function GET(req: NextRequest) {
    const { searchParams } = req.nextUrl;
    const subject = searchParams.get("subject")?.toLowerCase();
    const topic = searchParams.get("topic");
    const subtopic = searchParams.get("subtopic");
    const mode = (searchParams.get("mode") ?? "normal") as "normal" | "revision";

    if (!subject || !ALLOWED_SUBJECTS.has(subject)) {
        return NextResponse.json({ error: "Invalid subject" }, { status: 400 });
    }
    if (!topic) {
        return NextResponse.json({ error: "topic is required" }, { status: 400 });
    }
    if (mode !== "normal" && mode !== "revision") {
        return NextResponse.json({ error: "mode must be normal or revision" }, { status: 400 });
    }

    const filePath = path.join(process.cwd(), "data", "notes", `${subject}.json`);

    let data: SubjectNotesJSON;
    try {
        const raw = await fs.readFile(filePath, "utf-8");
        data = JSON.parse(raw);
    } catch {
        return NextResponse.json({ error: "Notes file not found" }, { status: 404 });
    }

    const notes = getNotes(data, topic, subtopic);
    if (!notes) {
        return NextResponse.json({ error: "No notes found for this topic/subtopic" }, { status: 404 });
    }

    const items = notes[mode];
    const topicLabel = subtopic ? `${topic} › ${subtopic}` : topic;
    const subjectName = subject.charAt(0).toUpperCase() + subject.slice(1);

    // Try to use Puppeteer if available; fall back to HTML
    try {
        const puppeteer = await import("puppeteer");
        const browser = await puppeteer.default.launch({
            headless: true,
            args: ["--no-sandbox", "--disable-setuid-sandbox"],
        });
        const page = await browser.newPage();
        await page.setContent(buildHtml(items, topicLabel, subjectName, mode), {
            waitUntil: "networkidle0",
        });
        const pdfBuffer = await page.pdf({
            format: "A4",
            printBackground: true,
            margin: { top: "0px", bottom: "0px", left: "0px", right: "0px" },
        });
        await browser.close();

        const filename = `${subjectName}_${topicLabel.replace(/[^\w\s]/g, "").replace(/\s+/g, "_")}_${mode}.pdf`;

        return new NextResponse(pdfBuffer, {
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="${filename}"`,
            },
        });
    } catch {
        // Puppeteer not available — return the HTML so the user can print-to-PDF
        const html = buildHtml(items, topicLabel, subjectName, mode);
        const filename = `${subjectName}_${topicLabel.replace(/[^\w\s]/g, "").replace(/\s+/g, "_")}_${mode}.html`;

        return new NextResponse(html, {
            headers: {
                "Content-Type": "text/html; charset=utf-8",
                "Content-Disposition": `attachment; filename="${filename}"`,
            },
        });
    }
}